//priority: 1001

const air = 'minecraft:air';

// priority of which mod output should come from, if applicable
const modPriorities = [
    'minecraft',
    'antimatter',
    'gregtech',
    'antimatter_shared',
    'kubejs',
    'quark',
    'tconstruct',
    'appliedenergistics2',
    'immersiveengineering',
    'biomesoplenty',
    'integrateddynamics',
    'beyond_earth'
];

// Used for recipes/tags that use colors
const colors = [
    'black',
    'blue',
    'brown',
    'cyan',
    'gray',
    'green',
    'light_blue',
    'light_gray',
    'lime',
    'magenta',
    'orange',
    'pink',
    'purple',
    'red',
    'white',
    'yellow'
];

// Quark Crystal Cluster Colors

const quark_crystal_colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet', 'white', 'black'];

const materialsToUnify = [
    'stone',
    'iron',
    'gold',
    'copper',
    'coal',
    'diamond',
    'emerald',
    'lapis',
    'redstone',
    'quartz',
    'netherite_scrap',
    'aluminium',
    'beryllium',
    'bismuth',
    'cobalt',
    'iridium',
    'lead',
    'manganese',
    'molybdenum',
    'neodymium',
    'nickel',
    'palladium',
    'platinum',
    'silver',
    'thorium',
    'titanium',
    'uranium_238',
    'graphite',
    'lithium',
    'sulfur',
    'tin',
    'zinc',
    'oilsands',
    'almandine',
    'andradite',
    'banded_iron',
    'brown_limonite',
    'calcite',
    'cassiterite',
    'chalcopyrite',
    'cobaltite',
    'cooperite',
    'galena',
    'garnierite',
    'grossular',
    'ilmenite',
    'rutile',
    'magnesite',
    'magnetite',
    'molybdenite',
    'phosphate',
    'pyrite',
    'pyrolusite',
    'pyrope',
    'saltpeter',
    'scheelite',
    'spessartine',
    'sphalerite',
    'stibnite',
    'tetrahedrite',
    'tungstate',
    'uraninite',
    'uvarovite',
    'wulfenite',
    'yellow_limonite',
    'vanadium_magnetite',
    'bastnasite',
    'pentlandite',
    'spodumene',
    'tantalite',
    'lepidolite',
    'glauconite',
    'bentonite',
    'pitchblende',
    'malachite',
    'barite',
    'talc',
    'soapstone',
    'blue_topaz',
    'green_sapphire',
    'lazurite',
    'ruby',
    'blue_sapphire',
    'sodalite',
    'tanzanite',
    'topaz',
    'olivine',
    'opal',
    'amethyst',
    'phosphorus',
    'red_garnet',
    'yellow_garnet',
    'cinnabar',
    'wrought_iron',
    'tungstensteel',
    'naquadah',
    'enriched_naquadah',
    'quartzite',
    'lignite_coal',
    'salt',
    'rock_salt',
    'bauxite',
    'oil_shale'
];

const planksToUnify = [
    'oak',
    'spruce',
    'birch',
    'jungle',
    'acacia',
    'dark_oak',
    'crimson',
    'warped',
    'fir',
    'redwood',
    'cherry',
    'mahogany',
    'jacaranda',
    'palm',
    'willow',
    'dead',
    'magic',
    'umbran',
    'hellbark',
    'menril'
];

const typesToUnify = ['nugget', 'ingot', 'gem', 'storage_block', 'ore', 'dust', 'gear', 'plate', 'rod'];

